# Generated by Django 5.2.12 on 2026-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_acessorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
