# Generated by Django 5.2.12 on 2026-03-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(blank=True, to='core.acessorio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cor'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modelo'),
        ),
    ]
